import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { useTranslation } from 'react-i18next';
import { BottomSheet } from './BottomSheet';
import styles from './EmployeeActionsSheet.module.css';
export function EmployeeActionsSheet({ employee, onClose, canChangeRole, canDeactivate, onChangeRole, onDeactivate, onRemove, }) {
    const { t } = useTranslation();
    const isOpen = Boolean(employee);
    return (_jsx(BottomSheet, { isOpen: isOpen, onClose: onClose, title: t('employees.sheet.actionsTitle'), subtitle: employee?.email, children: _jsxs("div", { className: styles.list, children: [canChangeRole ? (_jsxs("button", { type: "button", className: styles.row, onClick: onChangeRole, children: [_jsx("span", { className: styles.icon, "aria-hidden": true, children: _jsxs("svg", { width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, children: [_jsx("path", { d: "M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" }), _jsx("circle", { cx: "9", cy: "7", r: "4" }), _jsx("path", { d: "M22 21v-2a4 4 0 0 0-3-3.87M16 3.13a4 4 0 0 1 0 7.75" })] }) }), t('employees.actions.changeRole')] })) : null, canDeactivate ? (_jsxs(_Fragment, { children: [_jsxs("button", { type: "button", className: `${styles.row} ${styles.rowDanger}`, onClick: onDeactivate, children: [_jsx("span", { className: styles.icon, "aria-hidden": true, children: _jsxs("svg", { width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, children: [_jsx("circle", { cx: "12", cy: "12", r: "10" }), _jsx("path", { d: "M8 12h8" })] }) }), t('employees.actions.deactivate')] }), _jsxs("button", { type: "button", className: `${styles.row} ${styles.rowDanger}`, onClick: onRemove, children: [_jsx("span", { className: styles.icon, "aria-hidden": true, children: _jsx("svg", { width: "22", height: "22", viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 2, children: _jsx("path", { d: "M3 6h18M8 6V4a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M19 6v14a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V6" }) }) }), t('employees.actions.remove')] })] })) : null] }) }));
}
